site_name: pomegranate
theme: readthedocs
docs_dir: docs/
repo_url: http://github.com/jmschrei/pomegranate
site_url: http://pomegranate.readthedocs.org/en/stable/
site_description: pomegranate--efficient graphical models for python

pages:
- Home: index.md
#- Examples: examples.md
#- FAQ: faq.md
- Models:
  - Distributions: probability.md
#  - Naive Bayes: nb.md
#  - General Mixture Models: gmm.md
  - Hidden Markov Models: hmm.md
  - Bayesian Networks: bayesnet.md
  - Finite State Machines: fsm.md
